#! /bin/bash
echo Installing packages...

pip3 install discord
pip3 install requests
pip3 install asyncio
pip3 install discord_webhook

echo Packages installed! Opening repo...
open https://github.com/AstroOrbis/DiscordFuncs/tree/main